ALL_IDB2_val = datastore(fullfile(ALL_IDB, 'ALL_IDB1', 'im'),'FileExtensions', '.jpg','Type', 'image');

ALL_IDB2_cnn = datastore(fullfile(ALL_IDB, 'ALL_IDB2', 'cnn'),'FileExtensions', '.tif','Type', 'image');

augmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXScale',[1 2], ...
    'RandYReflection',true, ...
    'RandYScale',[1 2]);

net = alexnet;

inputSize = net.Layers(1).InputSize;

layersTransfer = net.Layers(1:end-3);
numClasses = 2;     % Background, WBCs

layers = [
    layersTransfer
    fullyConnectedLayer(numClasses,'WeightLearnRateFactor',20,'BiasLearnRateFactor',20)
    softmaxLayer
    classificationLayer];

pixelRange = [-30 30];
imageSize = [227 227 3];

imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);

augimdsTrain = augmentedImageDatastore(imageSize, inputSize(1:2),ALL_IDB2_cnn, ...
    'DataAugmentation',imageAugmenter);

augimdsValidation = augmentedImageDatastore(imageSize, inputSize(1:2),ALL_IDB2_val, ...
    'DataAugmentation',imageAugmenter);

options = trainingOptions('sgdm', ...
    'MiniBatchSize',10, ...
    'MaxEpochs',6, ...
    'InitialLearnRate',1e-4, ...
    'ValidationData',augimdsValidation, ...
    'ValidationFrequency',3, ...
    'ValidationPatience',Inf, ...
    'Verbose',false, ...
    'Plots','training-progress');

netTransfer = trainNetwork(augimdsTrain,layers,options);

